version: "3.7"

services:
  website:
    image: "nginx:alpine"
    volumes:
      - type: bind
        source: ./
        target: /usr/share/nginx/html
    ports:
      - "8088:80"
    environment:
      - NGINX_HOST=smartoakproject.com
      - NGINX_PORT=80